### ISSUE TITLE
OpenTK.WinFroms deprecated

### ISSUE THREAD

**Issue by KristenFred** [Digital-Production-Aachen/OVFSliceViewer#1]
Can be replaced with OpenTK.GLControl 4.0.0, worked fine for me.
https://www.nuget.org/packages/OpenTK.GLControl/4.0.0
https://www.nuget.org/packages/OpenTK.WinForms

**Comment by SebastianDirks** [comment]
Hi @KristenFred, thank you for the input. I did a maintenance update and updated all dependencies to the latest version. I switched to .net 8 and OpenTK.GLControl, which seems to support only OpenTK 4.8.2 currently, not yet releases 4.9.x. You can find the new release [here](https://github.com/Digital-Production-Aachen/OVFSliceViewer/releases/tag/v1.0.1).
